### ISSUE TITLE
Feature: ignore macOS theme

### ISSUE THREAD

**Issue by coolynx** [username0x0a/tweetduck#1]
I use Light theme on my Mac, however prefer the Dark ones on some specific apps, including TweetDuck. 🙄

Since v0.2.0 TweetDuck uses global macOS theme and ignores the Twitter setting.

I would appreciate to have an option - hidden config, special checkbox, menu or whatever to "Ignore macOS Theme" and use Twitter Theme setting instead.

Btw, thank you for TweetDuck! 🙇‍♂️

**Comment by username0x0a** [comment]
Hi, @coolynx, thanks for your feedback! 👍

Yea, this would certainly be an easy thing to handle, yet I really struggle to find an actual place where to collect these preferences 😅 I'd ideally integrate it to TweetDeck properties, yet that's a lot of (potentially breaking) JavaScript injection, other solution would mean making separate instances of dialogs where to toggle stuff. But I'll try to figure it asap somehow so this override could be in place. 👌
