### ISSUE TITLE
Feature: opening links outside the app in browser

### ISSUE THREAD

**Issue by coolynx** [username0x0a/tweetduck#2]
All links that TweetDuck can not handle it tries to open in a browser window.

This is good if I want to open some link, but there are some cases when it is unexpected and therefore annoying:

- in a column view a tweet with just a video with a play button and without a visible link (that looks exactly the same as the previous one that you just played), but this time is just a link to a Youtube video that fires up the browser to view it
- when you scroll a column and on the next touch for a scroll (not a click) unexpectedly opens some link, because app thinks that you want to open a link in the browser

In other cases you can guess that a link will be opened in a browser.

My guess is that the easiest way would be to have a setting - "Warn before opening links in the browser". In this case I have to click OK to open a new browser window for this link.

In old TweetDeck app when you clicked on a tweets image in a column you got that image in a full tweet page, but when you clicked again on that image it opened that image in the browser. Now in TweetDuck when you click on an image in the column view you get the full tweet page and when you click on that full image it just ignores such clicks. That's ok.

So, it could do the same with videos that are showed in columns and are not playable. When you click on a video play button that is not actually playable you got a full tweet page with a visible Youtube link. And in this case you can guess that it is not playable and are not going to click on it. It is annoying because you got a full page view with the same video preview and a visible Youtube link, but at least you did not get to the browser. 😅

Another option would be to get some kind of a visible warning that links are going to be opened outside. I know that is a Twitter issue.

Maybe it is possible to have some `userChrome.css` CSS file to override the default theme and mark outside links with some kind of warning ⚠️🔗icon. That would be a nice feature to have for those who want to use customized themes.

**Comment by username0x0a** [comment]
I've hot-fixed some embed videos & content (YouTube vids included) 👍 as this has been annoying for me as well. 😅 Ad external links opening – I can't really say where's the proper boundary – at this point it's really “safer” to just open unknown links in the default system browser. 🤔

Some CSS/JS injection would be definitely nice (maybe combine with my Tamperish code? 😆), but that's definitely a focus not for an immediate future.
